### PR TITLE
add a common help page for all CAS actions

### PR DESCRIPTION
**Pull request by mikemckiernan**
Instead of an error message for ?cas.simple.summary, we can provide a help page to the programming guides that show the actions.

### CODE REVIEW

**Comment by jld23** [comment]
@mikemckiernan so this will give generic help for all the functions listed in the alias (lines 2-341) but will still error for any function not listed here?

**Comment by mikemckiernan** [comment]
It will still show an error for any function that is not in the alias list.  That should be rare until the next Viya release.

**Comment by jld23** [comment]
I added a few tests and when I run them I get this error. what is the `\emph` tag supposed to do?

/Users/jadean/source/github/R-swat/man/generatedFunctions.Rd:344: Tag \emph not expected in code block

**Comment by mikemckiernan** [comment]
I've pulled test to my local repo.  I didn't get the message about the \emph tag before I made the PR.  Let's skip this PR for now and I'll come back with the test and an Rd file that cooperates for others too.

**Comment by mikemckiernan** [comment]
Maybe this PR can be saved.  I removed the \emph{} tags.  They worked fine in RStudio, but not in command-line R.  They were cosmetic and meant to indicate that the action set and action name were user-supplied.  I also corrected a typo.  

The tests ran OK, with seven skipped tests.  When the tests ran on command-line R, the test for help() waited for me to press q.

**Pull request merged**
